=== ehershey/development/csharp/XMLValidationTest/GenKeyIDSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="GenKeyIDSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="GenericKeyIDDictionary">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="GenericKeyIDList" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="GenericKeyIDPair" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                  </xs:sequence>
                  <xs:attribute use="required" name="PrimaryKeyVal" type="xs:integer" />
                  <xs:attribute use="required" name="SecondaryKeyVal" type="xs:integer" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute  use="required" name="ListName" type="xs:string"   />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ehershey/development/csharp/XMLValidationTest/GenKeyIDList.xml
<?xml version="1.0" encoding="utf-8"?>
<GenericKeyIDDictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="GenKeyIDSchema.xsd">
  <GenericKeyIDList ListName="TV.template">
    <GenericKeyIDPair PrimaryKeyVal="1" SecondaryKeyVal="2" />
    <GenericKeyIDPair PrimaryKeyVal="3" SecondaryKeyVal="4" />
  </GenericKeyIDList>
  <GenericKeyIDList ListName="Other.template">
    <GenericKeyIDPair PrimaryKeyVal="11" SecondaryKeyVal="-1" />
    <GenericKeyIDPair PrimaryKeyVal="330" SecondaryKeyVal="34" />
  </GenericKeyIDList>
  <GenericKeyIDList ListName="Another.template">
    <GenericKeyIDPair PrimaryKeyVal="330" SecondaryKeyVal="-1" />
    <GenericKeyIDPair PrimaryKeyVal="330" SecondaryKeyVal="-1" />
  </GenericKeyIDList>
</GenericKeyIDDictionary>
